services:
  - type: web
    name: Agora Token Server
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: APP_CERTIFICATE
        sync: false
